version: 2
updates:

  - package-ecosystem: pip
    directory: /catbuffer/parser
    schedule:
      interval: weekly
      day: sunday
    target-branch: dev
    labels: [catbuffer-parser]

  - package-ecosystem: pip
    directory: /client/catapult/scripts
    schedule:
      interval: weekly
      day: sunday
    target-branch: dev
    labels: [catapult]

  - package-ecosystem: npm
    directory: /client/rest
    schedule:
      interval: weekly
      day: sunday
    target-branch: dev
    labels: [rest]

  - package-ecosystem: pip
    directory: /jenkins/catapult
    schedule:
      interval: weekly
      day: sunday
    target-branch: dev
    labels: [jenkins]

  - package-ecosystem: pip
    directory: /linters/cpp
    schedule:
      interval: weekly
      day: sunday
    target-branch: dev
    labels: [linters]

  - package-ecosystem: pip
    directory: /linters/python
    schedule:
      interval: weekly
      day: sunday
    target-branch: dev
    labels: [linters]

  - package-ecosystem: npm
    directory: /sdk/javascript/generator
    schedule:
      interval: weekly
      day: sunday
    target-branch: dev
    labels: [sdk-javascript]

  - package-ecosystem: pip
    directory: /sdk/python
    schedule:
      interval: weekly
      day: sunday
    target-branch: dev
    labels: [sdk-python]
