version: 2
updates:

  - package-ecosystem: pip
    directory: /catbuffer/parser
    schedule:
      interval: weekly
      day: sunday
    target-branch: dev
    labels: [catbuffer-parser]
    commit-message:
      prefix: '[dependency]'

  - package-ecosystem: pip
    directory: /client/catapult/scripts
    schedule:
      interval: weekly
      day: sunday
    target-branch: dev
    labels: [catapult]
    commit-message:
      prefix: '[dependency]'

  - package-ecosystem: npm
    directory: /client/rest
    schedule:
      interval: weekly
      day: sunday
    target-branch: dev
    labels: [rest]
    versioning-strategy: increase
    commit-message:
      prefix: '[dependency]'

  - package-ecosystem: pip
    directory: /jenkins/catapult
    schedule:
      interval: weekly
      day: sunday
    target-branch: dev
    labels: [jenkins]
    commit-message:
      prefix: '[dependency]'

  - package-ecosystem: pip
    directory: /linters/cpp
    schedule:
      interval: weekly
      day: sunday
    target-branch: dev
    labels: [linters]
    commit-message:
      prefix: '[dependency]'

  - package-ecosystem: pip
    directory: /linters/python
    schedule:
      interval: weekly
      day: sunday
    target-branch: dev
    labels: [linters]
    commit-message:
      prefix: '[dependency]'

  - package-ecosystem: npm
    directory: /sdk/javascript
    schedule:
      interval: weekly
      day: sunday
    target-branch: dev
    labels: [sdk-javascript]
    versioning-strategy: increase
    commit-message:
      prefix: '[dependency]'

  - package-ecosystem: pip
    directory: /sdk/javascript/generator
    schedule:
      interval: weekly
      day: sunday
    target-branch: dev
    labels: [sdk-javascript]
    commit-message:
      prefix: '[dependency]'

  - package-ecosystem: pip
    directory: /sdk/python
    schedule:
      interval: weekly
      day: sunday
    target-branch: dev
    labels: [sdk-python]
    commit-message:
      prefix: '[dependency]'

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: sunday
    target-branch: dev
    commit-message:
      prefix: '[dependency]'
