language: python

python:
  - 3.7

env:
  global:
    RELEASE_BRANCH=main
    DEV_BRANCH=dev
    TEST_VECTORS_ROOT=$HOME/nemtech/test-vectors
    CATBUFFER_SCHEMAS=$HOME/catbuffer-schemas

cache: pip

addons:
  apt:
    packages:
    - zbar-tools

install:
  - pip install -r lint_requirements.txt
  - pip install -r requirements.txt

jobs:
  include:
    - stage: lint
      script:
        - sh ./lint.sh

    - stage: test
      name: unit tests
      script:
        - python3 -m unittest discover -v

    - name: catbuffer test vectors
      script:
        - git clone --depth=1 https://github.com/symbol/catbuffer-schemas.git $CATBUFFER_SCHEMAS
        - PYTHONPATH=. pytest generator

    - name: test vectors
      if: branch = env(DEV_BRANCH) OR branch = env(RELEASE_BRANCH)
      script:
        - git clone --depth=1 --branch=main https://github.com/nemtech/test-vectors.git $TEST_VECTORS_ROOT
        - python3 -m tests.vectors.all --blockchain nem --vectors "$TEST_VECTORS_ROOT/nem"
        - python3 -m tests.vectors.all --blockchain symbol --vectors "$TEST_VECTORS_ROOT/symbol"

    - stage: run examples
      script:
       - PYTHONPATH=. python examples/bip32_keypair.py
       - PYTHONPATH=. python examples/transaction_aggregate.py --private examples/resources/zero.sha256.txt
       - PYTHONPATH=. python examples/transaction_multisig.py
       - PYTHONPATH=. python examples/transaction_sign.py --blockchain=nem
       - PYTHONPATH=. python examples/transaction_sign.py --blockchain=symbol

    - stage: alpha / dev package
      name: alpha / dev package
      if: branch = env(DEV_BRANCH)
      script: echo deployment
      before_deploy:
        - sed -i "s/^\([0-9]\+.[0-9]\+.[0-9]\+\).*/\1a${TRAVIS_BUILD_NUMBER}/" version.txt
        - git add version.txt
        - git commit -m "automatic travis version bump"
      deploy:
        on:
          branch: $DEV_BRANCH
        provider: pypi
        username: $PYPI_USER
        password: $PYPI_PASS
        distributions: sdist bdist_wheel

    - stage: release package
      name: release package
      if: branch = env(RELEASE_BRANCH) AND type = api
      script: echo deployment
      deploy:
        on:
          branch: $RELEASE_BRANCH
        provider: pypi
        username: $PYPI_USER
        password: $PYPI_PASS
        distributions: sdist bdist_wheel
